openapi: 3.0.3
info:
  title: Swagger Petstore - OpenAPI 3.0
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
servers:
  - url: https://petstore3.swagger.io/api/v3
tags:
  - name: UserLikedPlace
    description: User liked place user controller
paths:
  /v1/user-liked-place:
    get:
      security:
        - BearerAuth: []
      tags:
        - UserLikedPlace
      summary: Get liked places of user
      operationId: getLikedPlaces
      x-spring-paginated: true
      parameters:
        - name: page
          in: query
          required: false
          style: form
          schema:
            type: integer
            format: int32
            minimum: 0
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PageUserPlaceResponse"
components:
  schemas:
    BasePage:
      type: object
      required:
        - totalPages
        - size
      properties:
        totalPages:
          type: integer
          format: int32
          default: 0
        size:
          type: integer
          format: int32
          default: 0
    UserPlaceResponse:
      required:
        - id
      type: object
      properties:
        id:
          type: string
    PageUserPlaceResponse:
      required:
        - content
      allOf:
        - $ref: "#/components/schemas/BasePage"
      type: object
      x-spring-paginated: true
      properties:
        content:
          type: array
          items:
            $ref: "#/components/schemas/UserPlaceResponse"
