openapi: 3.0.3
info:
  title: Test API Documentation
  description: Test API documentation
  termsOfService: "urn:tos"
  contact: {}
  license:
    name: Apache 2.0
    url: "http://www.apache.org/licenses/LICENSE-2.0"
  version: "1.0"
tags:
  - name: User
    description: User controller
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
  schemas:
    ErrorResponse:
      required:
        - errors
      type: object
      properties:
        errorModel:
          $ref: "#/components/schemas/ErrorModel"
    ErrorModel:
      required:
        - errorCode
        - defaultErrorMessage
        - params
      type: object
      properties:
        errorCode:
          $ref: "#/components/schemas/ErrorCodes"
        message:
          type: string
        descriptors:
          type: array
          items:
            type: string
    ErrorCodes:
      type: string
      enum:
        - BAD_REQUEST_ERROR
        - MALFORMED_DATA
    UserPlaceResponse:
      required:
        - id
        - name
        - couponCount
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        couponCount:
          type: integer
        description:
          type: string

paths:
  /v1/promoted-places/daily-promoted-place:
    get:
      security:
        - BearerAuth: []
      tags:
        - UserPromotedPlace
      summary: Get daily promoted place
      operationId: getDailyPromotedPlace
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserPlaceResponse"
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
